version: '3'

services:
  db:
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql:delegated
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: ./
    ports:
      - "8000:80"  
    volumes:
      - ./app:/var/www/html:cached
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:cached
      - ./logs:/logs:delegated
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      FS_METHOD: direct
      # XDEBUG_CONFIG: "remote_host=10.0.75.1"

volumes:
  mariadb: